---
# References:
# - https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

name: Build

on:
  workflow_call:
    inputs:
      BRANCH_NAME:
        default: master
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.BRANCH_NAME }}

      - name: Download env file
        uses: actions/download-artifact@v4
        with:
          name: env_artifact

      - name: Install dependencies
        shell: bash
        run: yarn install

      - name: Build the project
        shell: bash
        run: yarn build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist_artifact
          path: dist
          if-no-files-found: error
